name: ycbase
description: something baseWidget
version: 0.0.5
homepage: https://github.com/wq95230/ycbase.git

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"


dependencies:
  cached_network_image: ^3.3.0

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0



# The following section is specific to Flutter packages.
flutter:


