name: ycdb
description: A new Flutter package project.
version: 0.0.1
homepage: https://github.com/wq95230/ycbase

environment:
  sdk: '>=3.1.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0



# The following section is specific to Flutter packages.
flutter:


